import { useState, useEffect } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useCompanyMembers } from "@/hooks/useCompanyMembers";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { format } from "date-fns";
import { Plus, RefreshCw, Pause, Play, CheckCircle, Trash2, Loader2 } from "lucide-react";
import { toast } from "sonner";

export function FinanceRecurring() {
  const [dialogOpen, setDialogOpen] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [itemToDelete, setItemToDelete] = useState<any>(null);
  const [generating, setGenerating] = useState(false);
  const [formData, setFormData] = useState({
    name: "",
    type: "expense",
    amount: "",
    period: "monthly",
    start_date: format(new Date(), "yyyy-MM-dd"),
    end_date: "",
    due_day: "1",
    project_id: "",
    client_id: "",
  });
  const queryClient = useQueryClient();
  const { memberIds } = useCompanyMembers();

  const { data: recurringItems, isLoading } = useQuery({
    queryKey: ["finance-recurring", memberIds],
    queryFn: async () => {
      if (memberIds.length === 0) return [];
      const { data, error } = await supabase
        .from("recurring_budget")
        .select("*, projects(title), clients(name)")
        .in("created_by", memberIds)
        .order("created_at", { ascending: false });
      
      if (error) throw error;
      return data || [];
    },
    enabled: memberIds.length > 0,
  });

  const { data: projects } = useQuery({
    queryKey: ["company-projects-list"],
    queryFn: async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) return [];
      const { data: memberships } = await supabase.from("company_members").select("company_id").eq("user_id", session.user.id).limit(1);
      const cid = memberships?.[0]?.company_id;
      if (!cid) return [];
      const { data, error } = await supabase.from("projects").select("id, title").eq("company_id", cid).order("title");
      if (error) throw error;
      return data || [];
    },
  });

  const { data: clients } = useQuery({
    queryKey: ["company-clients-list"],
    queryFn: async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) return [];
      const { data: memberships } = await supabase.from("company_members").select("company_id").eq("user_id", session.user.id).limit(1);
      const cid = memberships?.[0]?.company_id;
      if (!cid) return [];
      const { data, error } = await supabase.from("clients").select("id, name").eq("company_id", cid).order("name");
      if (error) throw error;
      return data || [];
    },
  });

  // No auto-generation on mount - entries are generated by cron job on due_day

  const handleSubmit = async () => {
    if (!formData.name || !formData.amount) {
      toast.error("Please fill in all required fields");
      return;
    }

    setGenerating(true);
    try {
      const { data: session } = await supabase.auth.getSession();
      if (!session.session) throw new Error("Not authenticated");

      const { data: newRecurring, error } = await supabase.from("recurring_budget").insert({
        name: formData.name,
        type: formData.type,
        amount: parseFloat(formData.amount),
        period: formData.period,
        start_date: formData.start_date,
        end_date: formData.end_date || null,
        due_day: parseInt(formData.due_day),
        project_id: formData.project_id || null,
        client_id: formData.client_id || null,
        created_by: session.session.user.id,
      }).select().single();

      if (error) throw error;

      // No immediate entry generation - will be created by cron on due_day

      toast.success("Recurring budget created and entry generated");
      setDialogOpen(false);
      setFormData({
        name: "",
        type: "expense",
        amount: "",
        period: "monthly",
        start_date: format(new Date(), "yyyy-MM-dd"),
        end_date: "",
        due_day: "1",
        project_id: "",
        client_id: "",
      });
      queryClient.invalidateQueries({ queryKey: ["finance-recurring"] });
      queryClient.invalidateQueries({ queryKey: ["finance-expenses"] });
      queryClient.invalidateQueries({ queryKey: ["finance-income"] });
    } catch (error: any) {
      toast.error(error.message || "Failed to create recurring budget");
    } finally {
      setGenerating(false);
    }
  };

  const handleStatusChange = async (id: string, newStatus: string) => {
    try {
      const { error } = await supabase
        .from("recurring_budget")
        .update({ status: newStatus })
        .eq("id", id);

      if (error) throw error;

      toast.success(`Status updated to ${newStatus}`);
      queryClient.invalidateQueries({ queryKey: ["finance-recurring"] });
    } catch (error: any) {
      toast.error(error.message || "Failed to update status");
    }
  };

  const handleDeleteRecurring = async () => {
    if (!itemToDelete) return;
    
    try {
      const { error } = await supabase
        .from("recurring_budget")
        .delete()
        .eq("id", itemToDelete.id);

      if (error) throw error;

      toast.success("Recurring budget deleted successfully");
      setDeleteDialogOpen(false);
      setItemToDelete(null);
      queryClient.invalidateQueries({ queryKey: ["finance-recurring"] });
    } catch (error: any) {
      toast.error(error.message || "Failed to delete recurring budget");
    }
  };

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat("id-ID", {
      style: "currency",
      currency: "IDR",
      minimumFractionDigits: 0,
    }).format(value);
  };

  const getPeriodLabel = (period: string) => {
    const labels: Record<string, string> = {
      weekly: "Mingguan",
      monthly: "Bulanan",
      yearly: "Tahunan",
      custom: "Custom"
    };
    return labels[period] || period;
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "active": return "bg-green-500";
      case "paused": return "bg-yellow-500";
      case "completed": return "bg-muted";
      default: return "bg-muted";
    }
  };

  const getStatusLabel = (status: string) => {
    switch (status) {
      case "active": return "Aktif";
      case "paused": return "Di-pause";
      case "completed": return "Selesai";
      default: return status;
    }
  };

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="flex items-center gap-2">
          <RefreshCw className="h-5 w-5" />
          Recurring Budget
        </CardTitle>
        <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="h-4 w-4 mr-2" />
              Tambah Recurring
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Tambah Recurring Budget</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 max-h-[60vh] overflow-y-auto">
              <div className="space-y-2">
                <Label>Nama *</Label>
                <Input
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  placeholder="contoh: Sewa Kantor, Retainer Fee"
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Tipe *</Label>
                  <Select value={formData.type} onValueChange={(v) => setFormData({ ...formData, type: v })}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="expense">Pengeluaran</SelectItem>
                      <SelectItem value="income">Pemasukan</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Jumlah (IDR) *</Label>
                  <Input
                    type="number"
                    value={formData.amount}
                    onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                  />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Periode *</Label>
                  <Select value={formData.period} onValueChange={(v) => setFormData({ ...formData, period: v })}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="weekly">Mingguan</SelectItem>
                      <SelectItem value="monthly">Bulanan</SelectItem>
                      <SelectItem value="yearly">Tahunan</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Dibayar Setiap Tanggal</Label>
                  <Input
                    type="number"
                    min="1"
                    max="31"
                    value={formData.due_day}
                    onChange={(e) => setFormData({ ...formData, due_day: e.target.value })}
                    placeholder="1-31"
                  />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Tanggal Mulai *</Label>
                  <Input
                    type="date"
                    value={formData.start_date}
                    onChange={(e) => setFormData({ ...formData, start_date: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label>Tanggal Selesai (Opsional)</Label>
                  <Input
                    type="date"
                    value={formData.end_date}
                    onChange={(e) => setFormData({ ...formData, end_date: e.target.value })}
                  />
                </div>
              </div>
              <div className="space-y-2">
                <Label>Project (Opsional)</Label>
                <Select value={formData.project_id || "none"} onValueChange={(v) => setFormData({ ...formData, project_id: v === "none" ? "" : v })}>
                  <SelectTrigger>
                    <SelectValue placeholder="Pilih project" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="none">Tidak ada</SelectItem>
                    {projects?.map((p) => (
                      <SelectItem key={p.id} value={p.id}>{p.title}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Client (Opsional)</Label>
                <Select value={formData.client_id || "none"} onValueChange={(v) => setFormData({ ...formData, client_id: v === "none" ? "" : v })}>
                  <SelectTrigger>
                    <SelectValue placeholder="Pilih client" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="none">Tidak ada</SelectItem>
                    {clients?.map((c) => (
                      <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <p className="text-sm text-muted-foreground">
                Entry akan otomatis muncul di {formData.type === "expense" ? "Expenses" : "Income"} setiap tanggal {formData.due_day || "1"} setiap bulan. Anda tinggal mark as {formData.type === "expense" ? "paid" : "received"}.
              </p>
              <Button onClick={handleSubmit} className="w-full" disabled={generating}>
                {generating && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
                Buat Recurring Budget
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <div className="text-center py-8 text-muted-foreground">Loading...</div>
        ) : recurringItems && recurringItems.length > 0 ? (
          <div className="rounded-md border overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Nama</TableHead>
                  <TableHead>Tipe</TableHead>
                  <TableHead className="text-right">Jumlah</TableHead>
                  <TableHead>Periode</TableHead>
                  <TableHead>Tgl Bayar</TableHead>
                  <TableHead>Durasi</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Aksi</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {recurringItems.map((item) => (
                  <TableRow key={item.id}>
                    <TableCell className="font-medium">{item.name}</TableCell>
                    <TableCell>
                      <Badge className={item.type === "income" ? "bg-green-500" : "bg-destructive"}>
                        {item.type === "income" ? "Pemasukan" : "Pengeluaran"}
                      </Badge>
                    </TableCell>
                    <TableCell className={`text-right font-medium ${item.type === "income" ? "text-green-500" : "text-destructive"}`}>
                      {formatCurrency(item.amount)}
                    </TableCell>
                    <TableCell>{getPeriodLabel(item.period)}</TableCell>
                    <TableCell>Tgl {item.due_day || 1}</TableCell>
                    <TableCell className="text-sm">
                      {format(new Date(item.start_date), "dd/MM/yy")}
                      {item.end_date && ` - ${format(new Date(item.end_date), "dd/MM/yy")}`}
                      {!item.end_date && " - ∞"}
                    </TableCell>
                    <TableCell>
                      <Badge className={getStatusColor(item.status)}>
                        {getStatusLabel(item.status)}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <div className="flex gap-1">
                        {item.status === "active" && (
                          <Button size="sm" variant="ghost" onClick={() => handleStatusChange(item.id, "paused")} title="Pause">
                            <Pause className="h-4 w-4" />
                          </Button>
                        )}
                        {item.status === "paused" && (
                          <Button size="sm" variant="ghost" onClick={() => handleStatusChange(item.id, "active")} title="Aktifkan">
                            <Play className="h-4 w-4" />
                          </Button>
                        )}
                        {item.status !== "completed" && (
                          <Button size="sm" variant="ghost" onClick={() => handleStatusChange(item.id, "completed")} title="Selesai">
                            <CheckCircle className="h-4 w-4" />
                          </Button>
                        )}
                        <Button 
                          size="sm" 
                          variant="ghost" 
                          className="text-destructive hover:text-destructive"
                          onClick={() => {
                            setItemToDelete(item);
                            setDeleteDialogOpen(true);
                          }}
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        ) : (
          <div className="text-center py-12 text-muted-foreground">
            <RefreshCw className="h-12 w-12 mx-auto mb-4 opacity-50" />
            <p>Belum ada recurring budget</p>
          </div>
        )}
      </CardContent>

      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Hapus Recurring Budget</AlertDialogTitle>
            <AlertDialogDescription>
              Apakah Anda yakin ingin menghapus "{itemToDelete?.name}"? 
              Entry yang sudah di-generate tidak akan terhapus.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Batal</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDeleteRecurring}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Hapus
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </Card>
  );
}
